DROP TABLE IF EXISTS research.company_person;
DROP TABLE IF EXISTS project.base_index;
DROP TABLE IF EXISTS project.key_value_set_values;
DROP TABLE IF EXISTS project.key_value;
DROP TABLE IF EXISTS project.operator_set_operator;
DROP TABLE IF EXISTS project.operator;
DROP TABLE IF EXISTS project.project_person;
DROP TABLE IF EXISTS project.analysis_configuration;
DROP TABLE IF EXISTS project.operator_set;
DROP TABLE IF EXISTS project.key_value_set;
DROP TABLE IF EXISTS project.base;
DROP TABLE IF EXISTS project.algorithm_mask;
DROP TABLE IF EXISTS project.analysis;
DROP TABLE IF EXISTS project.project;
DROP TABLE IF EXISTS research.person;
DROP TABLE IF EXISTS project.dataset_column;
DROP TABLE IF EXISTS project.dataset;
DROP TABLE IF EXISTS research.company_research_category;
DROP TABLE IF EXISTS research.research_category;
DROP TABLE IF EXISTS research.company_type CASCADE ;
DROP TABLE IF EXISTS research.company CASCADE ;

