// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package apollo

import (
	"database/sql"
	"time"
)

type ProjectAlgorithmMask struct {
	AlgorithmMaskID int32     `json:"algorithm_mask_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type ProjectAnalysis struct {
	AnalysisID   int32          `json:"analysis_id"`
	ProjectID    sql.NullInt32  `json:"project_id"`
	AnalysisName string         `json:"analysis_name"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"created_at"`
}

type ProjectAnalysisConfiguration struct {
	AnalysisID           int32         `json:"analysis_id"`
	AlgorithmMaskID      sql.NullInt32 `json:"algorithm_mask_id"`
	DatasetID            sql.NullInt32 `json:"dataset_id"`
	OutcomeColumnID      sql.NullInt32 `json:"outcome_column_id"`
	OperatorSetID        sql.NullInt32 `json:"operator_set_id"`
	KeyValueID           sql.NullInt32 `json:"key_value_id"`
	BaseID               sql.NullInt32 `json:"base_id"`
	MinCache             sql.NullInt32 `json:"min_cache"`
	MaxCache             sql.NullInt32 `json:"max_cache"`
	MinHeatMap           sql.NullInt32 `json:"min_heat_map"`
	MaxHeatMap           sql.NullInt32 `json:"max_heat_map"`
	RecombinationPercent sql.NullInt32 `json:"recombination_percent"`
	HoldoutPercent       sql.NullInt32 `json:"holdout_percent"`
	MinPopulation        sql.NullInt32 `json:"min_population"`
	MaxPopulation        sql.NullInt32 `json:"max_population"`
	OverPopulationCycles sql.NullInt32 `json:"over_population_cycles"`
	CreatedAt            time.Time     `json:"created_at"`
}

type ProjectBase struct {
	BaseID      int32          `json:"base_id"`
	BaseNumber  sql.NullInt32  `json:"base_number"`
	BaseName    sql.NullString `json:"base_name"`
	Description sql.NullString `json:"description"`
	Delimiter   sql.NullString `json:"delimiter"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProjectBaseIndex struct {
	BaseID    int32          `json:"base_id"`
	Index     int32          `json:"index"`
	Value     sql.NullString `json:"value"`
	CreatedAt time.Time      `json:"created_at"`
}

type ProjectDataset struct {
	DatasetID int32        `json:"dataset_id"`
	FilePath  string       `json:"file_path"`
	FileName  string       `json:"file_name"`
	Prepared  sql.NullBool `json:"prepared"`
	CreatedAt time.Time    `json:"created_at"`
}

type ProjectDatasetColumn struct {
	DatasetColumnID    int32         `json:"dataset_column_id"`
	DatasetID          sql.NullInt32 `json:"dataset_id"`
	OriginalColumnName string        `json:"original_column_name"`
	ReferenceName      string        `json:"reference_name"`
	CreatedAt          time.Time     `json:"created_at"`
}

type ProjectKeyValue struct {
	KeyValueID   int32          `json:"key_value_id"`
	KeyValueName string         `json:"key_value_name"`
	Description  sql.NullString `json:"description"`
	CsvList      string         `json:"csv_list"`
}

type ProjectKeyValueSet struct {
	KeyValueSetID      int32          `json:"key_value_set_id"`
	KeyValueSetName    string         `json:"key_value_set_name"`
	Description        sql.NullString `json:"description"`
	KeyValueGroupLimit sql.NullInt32  `json:"key_value_group_limit"`
	CreatedAt          time.Time      `json:"created_at"`
}

type ProjectKeyValueSetValues struct {
	KeyValueSetID int32 `json:"key_value_set_id"`
	KeyValueID    int32 `json:"key_value_id"`
}

type ProjectOperator struct {
	OperatorID   int32     `json:"operator_id"`
	OperatorCode string    `json:"operator_code"`
	OperatorName string    `json:"operator_name"`
	Description  string    `json:"description"`
	OperandCount int32     `json:"operand_count"`
	Pattern      string    `json:"pattern"`
	CreatedAt    time.Time `json:"created_at"`
}

type ProjectOperatorSet struct {
	OperatorSetID   int32          `json:"operator_set_id"`
	OperatorSetName string         `json:"operator_set_name"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ProjectOperatorSetOperator struct {
	OperatorSetID sql.NullInt32 `json:"operator_set_id"`
	OperatorID    sql.NullInt32 `json:"operator_id"`
}

// projects are one or more analysis efforts'
type ProjectProject struct {
	ProjectID                 int32          `json:"project_id"`
	CompanyResearchCategoryID sql.NullInt32  `json:"company_research_category_id"`
	ProjectName               string         `json:"project_name"`
	Description               sql.NullString `json:"description"`
	CreatedAt                 time.Time      `json:"created_at"`
}

type ProjectProjectPerson struct {
	ProjectID   int32          `json:"project_id"`
	PersonID    int32          `json:"person_id"`
	ProjectRole sql.NullString `json:"project_role"`
}

type ResearchCompany struct {
	CompanyID       int32         `json:"company_id"`
	CompanyTypeID   int32         `json:"company_type_id"`
	ParentCompanyID sql.NullInt32 `json:"parent_company_id"`
	CompanyName     string        `json:"company_name"`
	CreatedAt       time.Time     `json:"created_at"`
}

type ResearchCompanyPerson struct {
	CompanyPersonID int32          `json:"company_person_id"`
	CompanyID       sql.NullInt32  `json:"company_id"`
	PersonID        sql.NullInt32  `json:"person_id"`
	Title           sql.NullString `json:"title"`
	Email           string         `json:"email"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ResearchCompanyResearchCategory struct {
	CompanyResearchCategoryID int32         `json:"company_research_category_id"`
	CompanyID                 sql.NullInt32 `json:"company_id"`
	ResearchCategoryID        sql.NullInt32 `json:"research_category_id"`
	CreatedAt                 time.Time     `json:"created_at"`
}

type ResearchCompanyType struct {
	CompanyTypeID   int32          `json:"company_type_id"`
	CompanyTypeName string         `json:"company_type_name"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ResearchPerson struct {
	PersonID     int32     `json:"person_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PrimaryPhone string    `json:"primary_phone"`
	PrimaryEmail string    `json:"primary_email"`
	CreatedAt    time.Time `json:"created_at"`
}

type ResearchResearchCategory struct {
	ResearchCategoryID   int32          `json:"research_category_id"`
	ResearchCategoryName string         `json:"research_category_name"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
}

type ResearchTvCompany struct {
	CompanyID       int32         `json:"company_id"`
	CompanyTypeID   int32         `json:"company_type_id"`
	ParentCompanyID sql.NullInt32 `json:"parent_company_id"`
	CompanyName     string        `json:"company_name"`
	CreatedAt       time.Time     `json:"created_at"`
}

type ResearchTvCompanyPerson struct {
	CompanyPersonID int32          `json:"company_person_id"`
	CompanyID       sql.NullInt32  `json:"company_id"`
	PersonID        sql.NullInt32  `json:"person_id"`
	Title           sql.NullString `json:"title"`
	Email           string         `json:"email"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ResearchTvCompanyResearchCategory struct {
	ResearchCategoryID sql.NullInt32 `json:"research_category_id"`
	CompanyID          sql.NullInt32 `json:"company_id"`
	CreatedAt          time.Time     `json:"created_at"`
}

type ResearchTvCompanyType struct {
	CompanyTypeID   int32          `json:"company_type_id"`
	CompanyTypeName string         `json:"company_type_name"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ResearchTvPerson struct {
	PersonID     int32     `json:"person_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PrimaryPhone string    `json:"primary_phone"`
	PrimaryEmail string    `json:"primary_email"`
	CreatedAt    time.Time `json:"created_at"`
}

type ResearchTvResearchCategory struct {
	ResearchCategoryID   int32          `json:"research_category_id"`
	ResearchCategoryName string         `json:"research_category_name"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
}

type ResearchVwCompanyPersonDetail struct {
	CompanyPersonID int32          `json:"company_person_id"`
	CompanyID       sql.NullInt32  `json:"company_id"`
	CompanyName     string         `json:"company_name"`
	PersonID        sql.NullInt32  `json:"person_id"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Title           sql.NullString `json:"title"`
	Email           string         `json:"email"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ResearchVwCompanyResearchCategory struct {
	ResearchCategoryID   sql.NullInt32 `json:"research_category_id"`
	CompanyID            sql.NullInt32 `json:"company_id"`
	CompanyName          string        `json:"company_name"`
	ResearchCategoryName string        `json:"research_category_name"`
	CreatedAt            time.Time     `json:"created_at"`
}
