// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package apollo

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (ResearchCompany, error)
	CreateCompanyType(ctx context.Context, arg CreateCompanyTypeParams) (ResearchCompanyType, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (ResearchPerson, error)
	DeleteCompany(ctx context.Context, pID int32) error
	DeleteCompanyType(ctx context.Context, pID int32) error
	DeletePerson(ctx context.Context, pID int32) error
	GetCompany(ctx context.Context, pID int32) (ResearchCompany, error)
	GetCompanyType(ctx context.Context, pID int32) (ResearchCompanyType, error)
	GetPerson(ctx context.Context, pID int32) (ResearchPerson, error)
	ListCompanies(ctx context.Context) ([]ResearchCompany, error)
	ListCompanyTypes(ctx context.Context) ([]ResearchCompanyType, error)
	ListPerson(ctx context.Context) ([]ResearchPerson, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (ResearchCompany, error)
	UpdateCompanyType(ctx context.Context, arg UpdateCompanyTypeParams) (ResearchCompanyType, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (ResearchPerson, error)
}

var _ Querier = (*Queries)(nil)
